train:
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0005
  epochs: 10

data:
  image_size: 256 # Downscale to 128 for computing constraint
  channels: 3
  category: bottle

network:
  model: ConvAutoencoder

loss:
  loss_type: MSE

quantize:
  backend: fbgemm
  layers:
    - encoder.layers.12
    - decoder.layers.0
    - encoder.layers.9
